title: Yeonsu Jung
logo: /assets/img/logo.png
description: Postdoctoral Fellow at [Harvard Applied Math](https://seas.harvard.edu/person/yeonsu-jung)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
